import { createServer } from "miragejs";

export function makeServer() {
  createServer({
    routes() {
      this.namespace = "api"; 

      this.get("/users", () => [
        { id: 1, catogory:'paneer', imageUrl: 'https://b.zmtcdn.com/data/dish_photos/8ea/f94cf0a907caab12dad3984f31fcd8ea.jpg?output-format=webp', title: 'Kadhai paneer', rating: '4.3 *', about:'Heat oil in a pan/kadai and temper with the coriander seeds. You can crush it roughly or add whole too.Follow by adding ginger and give a quick fry.Add chopped onion, green chillies slit and fry till onion turns transparent.In goes chopped tomatoes followed by salt.Add all the powders- chilli, coriander seeds, garam masala and turmeric.Fry till tomatoes turn gooey. Continue frying till oil oozes out and then add the cubed capsicum and fry for 1 minute.The crunchiness and colour should not change.Add the paneer cubes (paneer cubes should be kept immersed in hot water till use) and crush the kasoori methi within you palms and add it to it.'},
        { id: 2, catogory:'paneer', imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2021/04/malai-kofta-1.jpg', title: 'Malai Kofta', rating: '3.8 *' , about:'The prep work is time intensive, so plan ahead before making the recipe. You need to make the gravy base and the kofta.For the gravy you need onion paste, cashew paste and tomato paste. Cashew paste and tomato purée can be prepped ahead and refrigerated for a day.You can choose to make and shape the kofta mixture a day before and refrigerate them to ease your work. This is what I do on occasions. So next day you will only need to fry the kofta and make the gravy.'},
        { id: 3, catogory:'paneer', imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2021/02/matar-paneer-0.jpg', title: 'Matar paneer', rating: '3.5 *', about:'1 cup fresh or frozen Green Peas (matar) 3/4 cup (1/2-inch cubed) Paneer (cottage cheese)1 medium Onion, finely chopped 1 Green Chilli, chopped 2-3 cloves of Garlic 1/2 inch piece of Ginger, chopped2 medium Tomatoes, roughly chopped 5-6 Cashew Nuts, soaked in hot water for 20-30 minutes 1/2 teaspoon Red Chilli Powder 1/4 teaspoon Turmeric Powder 1 teaspoon Coriander Powder 1/4 teaspoon Garam Masala Powder' },
        { id: 4, catogory:'paneer', imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2013/06/shahi-paneer-1-1.jpg', title: 'Sahi paneer', rating: '4.2 *', about: 'Pressure cook together 1 onion, 3 tomatoes, 0.5 inch ginger and 6 cloves of garlic with ½ a cup of water. Cool and blend into a smooth paste. Heat 1 Tsp butter in a pan. Add 1 Tsp coriander powder, 0.5 Tsp red chilli powder, 0.5 Tsp kasuri methi and the 200 gms paneer cubes. Sauté for a few minutes.Add the onion-tomato paste, ½ cup water and salt to the paneer. Bring to a boil and simmer for 5 minutes. Then, add 2 tablespoons of cream and let it simmer for 2 minutes. What makes Shahi Paneer Recipe a standout dish? Soft and succulent Paneer takes the spotlight, embraced in a luscious blend of cream, and aromatic spices. Kasuri Methi adds its special touch, creating a symphony of flavours that elevate the Shahi Paneer.' },
       
        {id:5,  catogory:'dal', imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2012/01/punjabi-kadhi-pakora-recipe-easy.jpg', title: 'kadhi Pakora',rating: '4.3 *', about:'1. In a bowl take 1.5 cups sour curd or about 375 grams of curd. Whisk it well till smooth.2. Add 8 tablespoons of gram flour (besan), ½ teaspoon red chilli powder, ½ teaspoon turmeric powder, ½ teaspoon garam ma.'},
        {id:6, catogory:'dal', imageUrl: 'https://maunikagowardhan.co.uk/wp-content/uploads/2017/11/Black-Dal-Makhani-768x512.jpg', title: 'Dal Makhani',rating: '4.2 *', about:'280gms whole urad dal (black lentil)60gms red kidney beans1.5 litres water3 tbsp vegetable oil Pinch of asafoetida 1 green chilli slit lengthwise1 tsp cumin seeds coarsely ground 10 cloves of garlic finely chopped 210gms white onion finely chopped 220gms tomatoes finely chopped 3 tbsp tomato puree 1” piece of ginger finely chopped 1 tsp mild chilli powder ½ tsp garam masala powder 2 tbsp butter 60mls single cream  tbsp chopped coriander for garnish ½ “ginger slivers for garnish'}, 
        {id:8, catogory:'dal', imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2021/05/rajma-recipe-1.jpg', title: 'Rajma',rating: '4.1 *', about:'in a large kadai heat 1 tbsp ghee and saute 1 tsp cumin, 1 inch cinnamon and 5 cloves. add in 1 onion, 1 tsp ginger garlic paste, 1 chilli and saute until the onions turn golden brown. now add 2 cup tomato pulp. cover and cook for 10 minutes, or until the oil is separated. further keeping the flame on low add ¼ tsp turmeric, 1 tsp chilli powder, 1 tsp coriander powder, ½ tsp cumin powder, ½ tsp aamchur, ½ tsp garam masala and ½ tsp salt saute until the spices turn aromatic. add in cooked rajma and mix well. cover and simmer for 15 minutes or until the curry thickens. now add 1 tsp kasuri methi, 2 tbsp coriander and mix well. finally, enjoy rajma with hot jeera rice.'}, 
        {id:8, catogory:'dal', imageUrl: 'https://www.cookwithmanali.com/wp-content/uploads/2023/04/Punjabi-Chole-Masala-768x1164.jpg', title: 'Chole',rating: '4.1 *', about:'Soak raw chickpeas overnight in enough water to cover them. I soaked 2 cups of raw chickpeas and in the morning I had around 5 cups of it. Drain the water in which the chickpeas were soaked. 2 bay leaves , 5 green cardamom pods, 1-inch cinnamon stick, 4 to 5 whole black peppercorns, 2 black tea bags (these are added to give chole a darker color, skip if you don’t care about the color), Add around 5 cups of water and 1 teaspoon of salt.Stir and close the lid of the pressure cooker. Pressure cook at high heat for 1 to 2 whistles. After that, lower the heat to medium and let the chickpeas cook for another 10 to 12 minutes. Then turn off the heat and let the pressure release naturally'}, 
    
        {id: 9, catogory:'paratha',  imageUrl: 'https://www.cookingandme.com/wp-content/uploads/2011/02/5457754231_cb46f684831.webp', title: 'Aloo Paratha', rating: '4.1 *', about: '2 cups atta / whole wheat flour, Just over 1/2 cup water, 1 tsp salt or to taste, A few drops of oil, 2 medium sized potatoes, 1 tsp red chilli powder, 1/2 tsp jeera / cumin powder, 1/4 tsp ajwain / omam / carom seeds, 1/2 tsp chaat masala or garam masala, 1/2 tsp salt, A handful of coriander leaves'},
        {id: 10, catogory:'paratha', imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2013/01/onion-paratha.jpg', title: 'Onion Paratha', rating: '3.9 *', about: '1. Take 2 cups of whole wheat flour, 1 to 2 teaspoons of oil and salt as required in a mixing bowl. If you prefer, omit including oil in the dough, Add ⅓ to ½ cup of water in portions, Mix and then begin to knead the dough adding water bit by bit as needed, Knead a soft, smooth dough. The amount of water needed will depend upon the quality of the flour, Place the dough in a covered container and let it rest for 20 to 30 minutes. Meanwhile finely chop 1 large onion and 1 to 2 green chilies, Later pinch a medium-sized ball from the dough. Roll it between your palms to a smooth dough ball. Place it on a flour-dusted board or work surface and roll to a 3 to 4 inches round circle.'},
        {id: 11, catogory:'Paratha', imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2021/02/besan-chilla-1.jpg', title: 'Chilla', rating: '4.3 *', about: 'First, measure 1 cup of gram flour (besan) and pour it into a mixing bowl. Replace gram flour with chickpea flour if you do not have it. Next, add in your chopped veggies and herbs. It’s important to make sure all of these ingredients are FINELY chopped, otherwise, it becomes difficult to spread the chilla in the pan. ¼ cup finely chopped onions, ¼ cup finely chopped tomatoes, ½ teaspoon finely chopped ginger, ¼ cup finely chopped coriander leaves (cilantro), ½ teaspoon finely chopped green chilies or serrano peppers, Then it is time to mix in the spices, including 2 to 3 pinches of turmeric powder, ½ teaspoon carom seeds (ajwain) and ¼ teaspoon red chili powder. Also add salt as per your liking at this step.'},
        {id: 12, catogory:'Paratha', imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2021/06/paneer-paratha-1.jpg', title: 'Paneer paratha', rating: '4.0 *', about: 'Take 2 to 2.25 cups whole wheat flour, ½ teaspoon salt, 1 teaspoon ghee or oil in a mixing bowl, Pour about ½ cup of water,  Mix and begin to knead. Add more water if required and knead to a smooth soft pliable dough, Overall I added ⅔ cup water. I recommend not to add all the water at once. Add water bit by bit as you go on kneading the dough, Cover the bowl with a lid and allow the dough to rest for 20 to 30 minutes, Meanwhile while the dough is resting, prepare the stuffing. Grate 200 grams of paneer (Indian cottage cheese). If using frozen paneer then follow the package instructions, For the best taste and texture the paneer should be soft and fresh. A rancid paneer will make the paratha sour or bitter. Thus better not to use it'},

      ])
    }
  })
}     